# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  install-aws-cli:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pip3 install awscli

workflows:
  my-workflow:
    jobs:
      - install-aws-cli
